# Biomes Configuration ${project.version}
# This config file is dynamic and saved when the server is shutdown.
# You cannot edit it while the server is running because changes will
# be lost! Use in-game settings GUI or edit when server is offline.
#
# This indicates if advanced menu will be enabled in Biomes GUI when users choose
# biome or not. Advanced menu contains extra buttons that allows to choose biome
# change mode and range.
advanced-menu: true
#
# For advanced menu this indicate which mode will be active.
# If advanced menu is disabled or in biome set command update mode is not passed
# then update algorithm will use this value as update mode.
# Valid values are:
#     'ISLAND' - updates biome on whole island
#     'CHUNK' - updates biome on whole chunks around player
#     'SQUARE' - updates biome by block in given range
default-mode: ISLAND
#
# For advanced menu this indicate how large range will be set on GUI opening.
# If advanced menu is disabled or in biome set command update range is not set
# then update algorithm will use this value as update range.
default-size: 3
#
# This indicates if biome on island must be restored to default biome, if
# island changes owner and it does not have biome set ability.
# 'true' means that biome will be reset.
reset-biomes: false
#
# This indicates cool down in seconds between users can change biomes on their island.
cooldown: 60
#
# This variable allows to choose which biomes users can see in Biomes GUI.
# Valid values are:
#     'ALL' - there will be no hidden biomes. All biomes will be viewable in GUI.
#     'ACCESSIBLE' - only biomes that is unlocked via permission or other unlock type will be visible in GUI.
#     'TOGGLEABLE' - there will be button in GUI that allows users to switch from ALL to ACCESSIBLE modes.
biomes-visibility: ALL
uniqueId: config